# Generated by Django 4.1.5 on 2023-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_shorts_order_shorts_number_order_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_entered',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_exit',
            field=models.DateTimeField(),
        ),
    ]
