# Generated by Django 4.1.5 on 2023-07-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='debt',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
